import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { demoMemoryFiles, roles, sectionLabels } from './data';
import { buildBrief, buildItems, createAudit, isTaskValid } from './engine';
import type { Action, AgentId, Brief, FileKind, LocalFile, MemoryItem, ReviewChoice, RoleId, TargetEdit, TaskDraft, TaskStatus, TransferTask } from './types';
import './styles.css';

const blankDraft: TaskDraft = { sourceRole: '', targetRole: '', selectedAgent: '', memoryFiles: [], knowledgeFiles: [], prompt: '' };
const actionMeta: Record<Action, { label: string; tone: string }> = { transfer: { label: '迁移事实', tone: 'transfer' }, reframe: { label: '角色化改写', tone: 'reframe' }, review: { label: '人工确认', tone: 'review' }, block: { label: '阻断', tone: 'block' } };
const requiredChecks: (keyof Brief)[] = ['scope', 'risks', 'firstWeekPlan'];
const getRole = (id: RoleId | '') => roles.find((item) => item.id === id);
const shortPrompt = (prompt: string) => prompt.length > 92 ? `${prompt.slice(0, 92)}…` : prompt;

function App() {
  const [draft, setDraft] = useState<TaskDraft>(blankDraft);
  const [task, setTask] = useState<TransferTask | null>(null);
  const [screen, setScreen] = useState<'configure' | 'workspace' | 'published'>('configure');
  const [status, setStatus] = useState<TaskStatus>('configure');
  const [activeFileId, setActiveFileId] = useState<string | null>(null);
  const [activeItemId, setActiveItemId] = useState<string | null>(null);
  const [reviews, setReviews] = useState<Record<string, ReviewChoice>>({});
  const [reviewOpen, setReviewOpen] = useState(false);
  const [checks, setChecks] = useState<Record<string, boolean>>({});
  const [edits, setEdits] = useState<TargetEdit[]>([]);
  const [editing, setEditing] = useState<{ field: keyof Brief; index: number; text: string; reason: string } | null>(null);
  const [auditOpen, setAuditOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [publishedFilePath, setPublishedFilePath] = useState<string | null>(null);
  const knowledgeRef = useRef<HTMLInputElement>(null);
  const valid = Boolean(draft.selectedAgent) && isTaskValid(draft.sourceRole, draft.targetRole, draft.memoryFiles, draft.knowledgeFiles, draft.prompt);
  const items = useMemo(() => task ? buildItems(task) : [], [task]);
  const reviewItems = items.filter((item) => item.action === 'review');
  const allReviewsDone = reviewItems.every((item) => reviews[item.id]);
  const brief = useMemo(() => task ? buildBrief(task, reviews, edits) : null, [task, reviews, edits]);
  const allChecksDone = requiredChecks.every((field) => checks[field]);
  const activeFile = task ? [...task.memoryFiles, ...task.knowledgeFiles].find((file) => file.id === activeFileId) ?? task.memoryFiles[0] ?? task.knowledgeFiles[0] : null;
  const activeItem = items.find((item) => item.id === activeItemId) ?? null;
  const audit = task ? createAudit(task, reviews, edits, status === 'published') : [];
  useEffect(() => { if (status !== 'running') return; const timer = window.setTimeout(() => { setStatus('review'); setToast('已生成 FDE 交接草案：请先处理人工边界。'); }, 1200); return () => window.clearTimeout(timer); }, [status]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2800); return () => window.clearTimeout(timer); }, [toast]);
  const invalidateTask = (next: TaskDraft) => { setDraft(next); if (task) { setTask(null); setStatus('configure'); setReviews({}); setChecks({}); setEdits([]); } };
  const onField = <K extends keyof TaskDraft>(key: K, value: TaskDraft[K]) => invalidateTask({ ...draft, [key]: value });
  const readFiles = async (kind: FileKind, files: FileList | null) => { if (!files) return; const selected = Array.from(files).slice(0, 1); const loaded = await Promise.all(selected.map(async (file, index): Promise<LocalFile> => ({ id: `${kind}-${file.name}-${Date.now()}-${index}`, name: file.name, kind, origin: 'desktop_upload', pathLabel: '本地知识文件 · 已选择', content: await file.text(), size: file.size }))); invalidateTask({ ...draft, knowledgeFiles: loaded }); setToast(`已读取 ${loaded.length} 份本地知识文件`); };
  const removeFile = (kind: FileKind, id: string) => { const key = kind === 'agent_memory' ? 'memoryFiles' : 'knowledgeFiles'; invalidateTask({ ...draft, [key]: draft[key].filter((file) => file.id !== id) }); };
  const generateTask = () => { if (!valid) return; setTask({ ...draft, sourceRole: draft.sourceRole as RoleId, targetRole: draft.targetRole as RoleId, selectedAgent: draft.selectedAgent as AgentId, id: `handoff-${Date.now()}`, status: 'ready' }); setStatus('ready'); setToast('交接任务卡已生成。确认后再开始交接。'); };
  const start = () => { if (!task) return; setScreen('workspace'); setStatus('running'); setActiveFileId(task.memoryFiles[0]?.id ?? task.knowledgeFiles[0]?.id ?? null); };
  const saveEdit = () => { if (!editing || !brief || !editing.text.trim() || !editing.reason.trim()) return; const next = { field: editing.field, index: editing.index, before: brief[editing.field][editing.index], after: editing.text.trim(), reason: editing.reason.trim() }; setEdits((current) => [...current.filter((item) => !(item.field === next.field && item.index === next.index)), next]); setEditing(null); setToast('FDE 修改已保存，并保留理由与 Diff。'); };
  const goTargetCheck = () => { if (!allReviewsDone) { setReviewOpen(true); return; } setStatus('target_check'); setToast('FDE 可以检查、修改并确认目标工作记忆。'); };
  const publish = async () => { if (!allChecksDone || !task || !brief) return; try { const response = await fetch('/api/export-handoff', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ task: { sourceRoleLabel: getRole(task.sourceRole)?.label, targetRoleLabel: getRole(task.targetRole)?.label, prompt: task.prompt, files: [...task.memoryFiles, ...task.knowledgeFiles].map((file) => file.name) }, brief, reviews, edits }) }); const result = await response.json() as { filePath?: string; error?: string }; if (!response.ok || !result.filePath) throw new Error(result.error ?? '无法生成桌面交接文件。'); setPublishedFilePath(result.filePath); setStatus('published'); setScreen('published'); } catch (error) { setToast(error instanceof Error ? `导出失败：${error.message}` : '导出失败，请确认本地服务正在运行。'); } };
  const reset = () => { setDraft(blankDraft); setTask(null); setStatus('configure'); setScreen('configure'); setReviews({}); setChecks({}); setEdits([]); setPublishedFilePath(null); setToast(null); };
  return <><header className="topbar"><button className="brand" onClick={() => screen !== 'workspace' && setScreen('configure')}><span className="brand-mark">C</span>ContextBridge</button><div><span className="mode-pill"><i /> Demo Replay · Local files</span>{task && <button className="quiet-button" onClick={() => setAuditOpen(true)}>审计 {audit.length}</button>}</div></header>{screen === 'configure' && <main className="composer-page"><section className="composer-intro"><span className="eyebrow">跨角色 Context Bridge</span><h1>让 Context 跨越角色，<br />成为下一位的行动。</h1><p>ContextBridge 将任意角色的工作记忆，按目标角色的职责、风险边界与下一步动作重构；售前 → FDE 只是其中一条路径。</p></section><TaskComposer draft={draft} valid={valid} knowledgeRef={knowledgeRef} onField={onField} onFiles={readFiles} onRemove={removeFile} onGenerate={generateTask} />{task && <TaskCard task={task} onEdit={() => { setTask(null); setStatus('configure'); }} onStart={start} />}</main>}{screen === 'workspace' && task && brief && <Workspace task={task} status={status} items={items} activeFile={activeFile} activeItem={activeItem} brief={brief} reviews={reviews} checks={checks} edits={edits} onFile={setActiveFileId} onItem={setActiveItemId} onReview={() => setReviewOpen(true)} onTargetCheck={goTargetCheck} onCheck={(field) => setChecks((current) => ({ ...current, [field]: true }))} onEdit={(field, index) => setEditing({ field, index, text: brief[field][index], reason: '' })} onPublish={publish} />}{screen === 'published' && task && brief && <Published task={task} brief={brief} filePath={publishedFilePath} onReset={reset} />}{reviewOpen && <ReviewModal items={reviewItems} reviews={reviews} onChoose={(id, choice) => setReviews((current) => ({ ...current, [id]: choice }))} onClose={() => setReviewOpen(false)} />}{editing && <EditModal editing={editing} setEditing={setEditing} onClose={() => setEditing(null)} onSave={saveEdit} />}{auditOpen && <AuditDrawer events={audit} onClose={() => setAuditOpen(false)} />}{toast && <div className="toast">✓ {toast}</div>}</>;
}

function TaskComposer({ draft, valid, knowledgeRef, onField, onFiles, onRemove, onGenerate }: { draft: TaskDraft; valid: boolean; knowledgeRef: React.RefObject<HTMLInputElement | null>; onField: <K extends keyof TaskDraft>(key: K, value: TaskDraft[K]) => void; onFiles: (kind: FileKind, files: FileList | null) => void; onRemove: (kind: FileKind, id: string) => void; onGenerate: () => void }) { const targets = roles.filter((item) => item.id !== draft.sourceRole && (item.type === 'target' || item.type === 'both')); const chooseMemory = (file: LocalFile) => { const exists = draft.memoryFiles.some((item) => item.id === file.id); onField('memoryFiles', exists ? draft.memoryFiles.filter((item) => item.id !== file.id) : [...draft.memoryFiles, file]); }; return <section className="composer"><div className="composer-head"><div><span className="step">01 · TASK CONFIGURATION</span><h2>配置一次交接</h2></div></div><div className="role-grid"><RoleSelect label="源用户" value={draft.sourceRole} choices={roles.filter((item) => item.type === 'source' || item.type === 'both')} onChange={(value) => onField('sourceRole', value as RoleId)} /><div className="role-arrow">→</div><RoleSelect label="目标用户" value={draft.targetRole} choices={targets} onChange={(value) => onField('targetRole', value as RoleId)} /></div><div className="file-grid"><AgentMemoryPicker selectedAgent={draft.selectedAgent} files={draft.memoryFiles} onAgent={(agent) => { onField('selectedAgent', agent); if (agent !== 'codex') onField('memoryFiles', []); }} onToggle={chooseMemory} /><FileBucket title="02 · 本地知识文件" description="从本地电脑添加一份项目知识资料" files={draft.knowledgeFiles} kind="knowledge" inputRef={knowledgeRef} onPick={() => knowledgeRef.current?.click()} onFiles={onFiles} onRemove={onRemove} /></div><label className="prompt-box"><span>03 · 转换要求 <em>必填</em></span><textarea maxLength={500} value={draft.prompt} onChange={(event) => onField('prompt', event.target.value)} placeholder="例如：把售前叙述转换为 FDE 可启动的交付 Brief；区分确认事实、待确认项、风险和敏感信息。" /><small>{draft.prompt.length}/500 · 此要求会写入任务卡与审计记录</small></label><div className="composer-footer"><p>{valid ? '配置完整。生成任务卡后，才可开始交接。' : '请选择不同角色、Agent、记忆文件、1 份知识，并写下转换要求。'}</p><button className="primary-button" disabled={!valid} onClick={onGenerate}>生成交接任务卡 <span>→</span></button></div></section>; }
function RoleSelect({ label, value, choices, onChange }: { label: string; value: string; choices: typeof roles; onChange: (value: string) => void }) { const profile = getRole(value as RoleId); return <label className="role-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">请选择角色</option>{choices.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{profile ? profile.description : '选择后显示该角色的工作语言与重点。'}</small></label>; }
function AgentMemoryPicker({ selectedAgent, files, onAgent, onToggle }: { selectedAgent: AgentId | ''; files: LocalFile[]; onAgent: (agent: AgentId) => void; onToggle: (file: LocalFile) => void }) { const available = selectedAgent === 'codex' ? demoMemoryFiles : []; return <section className="file-bucket agent-picker"><div><span className="step">01 · Agent Memory</span><p>先选择 Agent，再从其记忆存储路径选择文件。</p></div><label className="agent-select">Agent<select value={selectedAgent} onChange={(event) => onAgent(event.target.value as AgentId)}><option value="">请选择 Agent</option><option value="codex">Codex（本地）</option><option value="cursor">Cursor Agent（Mock）</option><option value="claude_code">Claude Code（Mock）</option></select></label>{selectedAgent === 'codex' && <><div className="memory-path">Codex Memory Path<br /><code>~/.codex/agents/sales/memory/</code></div><div className="memory-catalog">{available.map((file) => <label key={file.id}><input type="checkbox" checked={files.some((item) => item.id === file.id)} onChange={() => onToggle(file)} /><span>✦</span><div><strong>{file.name}</strong><small>记忆文件 · {(file.size / 1024).toFixed(1)} KB</small></div></label>)}</div></>}{selectedAgent && selectedAgent !== 'codex' && <p className="empty-file">该 Agent 的 Mock 记忆路径暂无可选文件。</p>}</section>; }
function FileBucket({ title, description, files, kind, inputRef, onPick, onFiles, onRemove }: { title: string; description: string; files: LocalFile[]; kind: FileKind; inputRef: React.RefObject<HTMLInputElement | null>; onPick: () => void; onFiles: (kind: FileKind, files: FileList | null) => void; onRemove: (kind: FileKind, id: string) => void }) { return <section className="file-bucket"><div><span className="step">{title}</span><p>{description}</p></div><input ref={inputRef} type="file" multiple={false} accept=".md,.txt,.json" onChange={(event) => onFiles(kind, event.target.files)} /><button className="secondary-button" onClick={onPick}>选择知识文件</button><div className="selected-files">{files.length ? files.map((file) => <div className="selected-file" key={file.id}><span>▣</span><div><strong>{file.name}</strong><small>{file.pathLabel} · {(file.size / 1024).toFixed(1)} KB</small></div><button onClick={() => onRemove(kind, file.id)} aria-label={`移除 ${file.name}`}>×</button></div>) : <p className="empty-file">尚未选择文件</p>}</div></section>; }
function TaskCard({ task, onEdit, onStart }: { task: TransferTask; onEdit: () => void; onStart: () => void }) { return <section className="task-card"><div><span className="eyebrow">READY TO RUN</span><h2>待执行的交接任务</h2><div className="task-route"><strong>{getRole(task.sourceRole)?.label}</strong><span>→</span><strong>{getRole(task.targetRole)?.label}</strong></div><p>澄澈零售集团 / AtlasFlow 试点</p><div className="task-meta"><span>{task.selectedAgent === 'codex' ? 'Codex 记忆路径' : task.selectedAgent}</span><span>{task.memoryFiles.length} 份记忆</span><span>{task.knowledgeFiles.length} 份知识</span></div><blockquote>{shortPrompt(task.prompt)}</blockquote></div><div className="task-actions"><button className="secondary-button" onClick={onEdit}>编辑配置</button><button className="primary-button" onClick={onStart}>开始交接 <span>→</span></button></div></section>; }

function Workspace({ task, status, items, activeFile, activeItem, brief, reviews, checks, edits, onFile, onItem, onReview, onTargetCheck, onCheck, onEdit, onPublish }: { task: TransferTask; status: TaskStatus; items: MemoryItem[]; activeFile: LocalFile | null; activeItem: MemoryItem | null; brief: Brief; reviews: Record<string, ReviewChoice>; checks: Record<string, boolean>; edits: TargetEdit[]; onFile: (id: string) => void; onItem: (id: string) => void; onReview: () => void; onTargetCheck: () => void; onCheck: (field: keyof Brief) => void; onEdit: (field: keyof Brief, index: number) => void; onPublish: () => void }) { const checking = status === 'target_check'; const allChecksDone = requiredChecks.every((field) => checks[field]); const allFiles = [...task.memoryFiles, ...task.knowledgeFiles]; return <main className="workspace"><div className="workspace-head"><div><button className="back-link" onClick={() => window.location.reload()}>← 新建任务</button><span>任务快照 · {getRole(task.sourceRole)?.label} → {getRole(task.targetRole)?.label}</span></div><div className={`status-pill ${status}`}>{status === 'running' ? '正在转换本地 Context' : status === 'review' ? `待人工确认 ${items.filter((item) => item.action === 'review').length - Object.keys(reviews).length} 项` : checking ? 'FDE 正在检查' : '交接结果'}</div></div><div className="contrast-banner"><span>交接前：{getRole(task.sourceRole)?.label} 的工作语言</span><i>→</i><span>交接后：{getRole(task.targetRole)?.label} 的行动语言</span></div><div className="workspace-grid"><SourcePanel files={allFiles} activeFile={activeFile} activeItem={activeItem} onFile={onFile} /><BridgePanel status={status} items={items} activeItem={activeItem} onItem={onItem} onReview={onReview} /><BriefPanel task={task} status={status} brief={brief} checks={checks} edits={edits} onTargetCheck={onTargetCheck} onCheck={onCheck} onEdit={onEdit} onPublish={onPublish} allChecksDone={allChecksDone} /></div></main>; }
function SourcePanel({ files, activeFile, activeItem, onFile }: { files: LocalFile[]; activeFile: LocalFile | null; activeItem: MemoryItem | null; onFile: (id: string) => void }) { return <section className="panel source-panel"><div className="panel-head"><span className="step">交接前 · SOURCE</span><h2>售前怎么说</h2><p>原始本地记忆保留机会、感受、承诺和内部噪声。</p></div><div className="file-tabs">{files.map((file) => <button key={file.id} onClick={() => onFile(file.id)} className={activeFile?.id === file.id ? 'active' : ''}>{file.kind === 'agent_memory' ? '✦' : '▣'} {file.name}</button>)}</div>{activeFile && <div className="raw-file"><div className="file-origin">{activeFile.pathLabel}</div><pre>{activeFile.content}</pre></div>}{activeItem && <div className="source-focus"><span>当前证据</span><strong>“{activeItem.sourceText}”</strong></div>}</section>; }
function BridgePanel({ status, items, activeItem, onItem, onReview }: { status: TaskStatus; items: MemoryItem[]; activeItem: MemoryItem | null; onItem: (id: string) => void; onReview: () => void }) { const counts = (action: Action) => items.filter((item) => item.action === action).length; return <section className="panel bridge-panel"><div className="panel-head"><span className="step">受控翻译 · BRIDGE</span><h2>{status === 'running' ? '正在读取并判断…' : '每条信息如何处理'}</h2><p>不是摘要：每句话都要决定是否可迁移、如何改写、是否需人确认。</p></div>{status === 'running' ? <div className="working-state"><div className="pulse" /><strong>读取本地文件</strong><span>按角色边界检查承诺、判断和敏感信息</span></div> : <><div className="action-summary"><span>{counts('transfer')} 迁移</span><span>{counts('reframe')} 改写</span><span>{counts('review')} 人审</span><span>{counts('block')} 阻断</span></div><div className="decision-list">{items.map((item) => <button key={item.id} onClick={() => onItem(item.id)} className={`decision ${actionMeta[item.action].tone} ${activeItem?.id === item.id ? 'active' : ''}`}><span>{item.action === 'transfer' ? '↗' : item.action === 'reframe' ? '◇' : item.action === 'review' ? '!' : '×'}</span><div><small>{actionMeta[item.action].label} · {item.sourceFileName}</small><strong>{item.sourceText}</strong></div></button>)}</div>{activeItem && <div className="decision-detail"><span>目标角色表达</span><strong>{activeItem.action === 'block' ? '已阻断，不进入目标 Brief。' : activeItem.targetText}</strong><p>{activeItem.reason}</p></div>}<button className="review-button" onClick={onReview}>处理人工确认（{counts('review')} 项）</button></>}</section>; }
function BriefPanel({ task, status, brief, checks, edits, onTargetCheck, onCheck, onEdit, onPublish, allChecksDone }: { task: TransferTask; status: TaskStatus; brief: Brief; checks: Record<string, boolean>; edits: TargetEdit[]; onTargetCheck: () => void; onCheck: (field: keyof Brief) => void; onEdit: (field: keyof Brief, index: number) => void; onPublish: () => void; allChecksDone: boolean }) { const visible = status !== 'running'; const checking = status === 'target_check'; return <section className="panel brief-panel"><div className="panel-head"><span className="step">交接后 · TARGET</span><h2>{getRole(task.targetRole)?.label} 怎么接手</h2><p>把售前的叙述变成范围、依赖、风险和首周动作。</p></div>{visible ? <><div className="brief-content">{(Object.keys(brief) as (keyof Brief)[]).map((field) => <section className="brief-section" key={field}><div><h3>{sectionLabels[field]}</h3>{checking && requiredChecks.includes(field) && <small className={checks[field] ? 'checked' : 'unchecked'}>{checks[field] ? '已检查' : '待检查'}</small>}</div><ul>{brief[field].map((line, index) => <li className={edits.some((edit) => edit.field === field && edit.index === index) ? 'edited' : ''} key={`${field}-${index}`}><span>{line}</span>{checking && field !== 'blockedSummary' && <button onClick={() => onEdit(field, index)}>编辑</button>}</li>)}</ul>{checking && requiredChecks.includes(field) && <button className="confirm-link" onClick={() => onCheck(field)}>✓ 确认本区块</button>}</section>)}</div>{!checking ? <button className="primary-button full" onClick={onTargetCheck}>交给 {getRole(task.targetRole)?.label} 检查 <span>→</span></button> : <div className="publish-box"><span>{allChecksDone ? '三项接手检查已完成' : '请完成范围、风险、首周动作检查'}</span><button className="primary-button" disabled={!allChecksDone} onClick={onPublish}>发布交接包</button></div>}</> : <div className="brief-empty">等待 Bridge 完成本地 Context 转换。</div>}</section>; }
function ReviewModal({ items, reviews, onChoose, onClose }: { items: MemoryItem[]; reviews: Record<string, ReviewChoice>; onChoose: (id: string, choice: ReviewChoice) => void; onClose: () => void }) { const current = items.find((item) => !reviews[item.id]) ?? items[0]; if (!current) return null; const options: { value: ReviewChoice; label: string }[] = current.id === 'M-02' ? [{ value: 'reference', label: '作为当前参考，不承诺上线' }, { value: 'open', label: '继续标记为待确认' }] : current.id === 'M-06' ? [{ value: 'signal', label: '转为待验证信号' }, { value: 'open', label: '不迁移该判断' }] : [{ value: 'open', label: '保留为技术发现会澄清项' }, { value: 'reference', label: '作为硬约束候选' }]; const done = items.every((item) => reviews[item.id]); return <div className="overlay"><section className="modal review-modal"><div className="modal-head"><div><span className="eyebrow">HUMAN BOUNDARY</span><h2>这一步不让 Agent 自动决定</h2></div><button onClick={onClose}>×</button></div><div className="review-progress">已处理 {Object.keys(reviews).length}/{items.length}</div><blockquote>“{current.sourceText}”</blockquote><p>{current.reason}</p><div className="review-output"><small>若迁移给目标角色：</small>{current.targetText}</div><div className="choice-list">{options.map((option) => <button onClick={() => onChoose(current.id, option.value)} key={option.value}>{option.label}<span>→</span></button>)}</div><div className="modal-footer"><button className="secondary-button" onClick={onClose}>稍后处理</button><button className="primary-button" disabled={!done} onClick={onClose}>写入交接草案</button></div></section></div>; }

function EditModal({ editing, setEditing, onClose, onSave }: { editing: { field: keyof Brief; index: number; text: string; reason: string }; setEditing: (value: { field: keyof Brief; index: number; text: string; reason: string } | null) => void; onClose: () => void; onSave: () => void }) { return <div className="overlay"><section className="modal edit-modal"><div className="modal-head"><div><span className="eyebrow">FDE TARGET CHECK</span><h2>修订目标工作记忆</h2></div><button onClick={onClose}>×</button></div><label>FDE 修改后的内容<textarea value={editing.text} onChange={(event) => setEditing({ ...editing, text: event.target.value })} /></label><label>修改理由（必填）<input value={editing.reason} onChange={(event) => setEditing({ ...editing, reason: event.target.value })} placeholder="例如：上线日期必须等待技术发现会评估" /></label><p>保存后会保留 Agent 草案、FDE 修改和理由。</p><div className="modal-footer"><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" disabled={!editing.text.trim() || !editing.reason.trim()} onClick={onSave}>保存修改</button></div></section></div>; }
function AuditDrawer({ events, onClose }: { events: ReturnType<typeof createAudit>; onClose: () => void }) { return <div className="overlay right"><section className="drawer"><div className="modal-head"><div><span className="eyebrow">AUDIT TRAIL</span><h2>交接记录</h2></div><button onClick={onClose}>×</button></div>{events.map((event, index) => <div className={`audit-event ${event.tone ?? ''}`} key={`${event.title}-${index}`}><i /><div><small>{event.actor}</small><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</section></div>; }
function Published({ task, brief, filePath, onReset }: { task: TransferTask; brief: Brief; filePath: string | null; onReset: () => void }) { return <main className="published-page"><section className="published-card"><div className="success">✓</div><span className="eyebrow">HANDOFF READY</span><h1>交接包已发布</h1><p>{getRole(task.targetRole)?.label} 已审核并接手该任务快照。</p><div className="publish-note">完整交接文件已保存至桌面：<br /><code>{filePath ?? '正在生成…'}</code></div><div className="validation-list"><p><strong>客户要达成什么？</strong>{brief.scope[1] ?? brief.scope[0]}</p><p><strong>第一个技术依赖？</strong>{brief.dependencies[0]}</p><p><strong>不能承诺什么？</strong>具体上线日期与私有化交付方案。</p><p><strong>首周第一件事？</strong>{brief.firstWeekPlan[0]}</p></div><button className="primary-button" onClick={onReset}>新建另一项交接</button></section></main>; }

createRoot(document.getElementById('root')!).render(<App />);
